languageName: Türkçe
languageCode: tr
title: Bilgisayar Mühendisliği Bölümü | Boğaziçi Üniversitesi
weight: 1
params:
  about: " Translation "
  logo_text_main: Bilgisayar Mühendisliği
  logo_text_top: Boğaziçi Üniversitesi
  powered_by_text: >-
    Bu site [Hugo](https://gohugo.io) ve [Bootstrap](https://getbootstrap.com) ile tasarlandı
  social:
    - icon: twitter
      identifier: twitter
      url: https://twitter.com/Bogazici_CmpE
    - icon: github
      identifier: github
      url: https://github.com/bouncmpe
  footer:
    sections:
      - title: Boğaziçi Üniversitesi
        links:
          - title: Anasayfa
            url: http://www.boun.edu.tr
          - title: Mühendislik Fakültesi
            url: http://www.eng.boun.edu.tr/
          - title: Fen Bilimleri Enstitüsü
            url: http://www.fbe.boun.edu.tr
          - title: Kütüphane
            url: https://www.library.boun.edu.tr/
          - title: Bilişim Hizmetleri
            url: https://cc.boun.edu.tr/
          - title: Kampüs Haritası
            url: https://harita.boun.edu.tr/

      - title: Eğitim & Öğretim
        links:
          - title: Akademik Takvim
            url: https://akademiktakvim.boun.edu.tr/
          - title: Kayıt İşleri
            url: https://registration.boun.edu.tr/
          - title: Moodle
            url: https://moodle.boun.edu.tr/
          - title: Uzaktan Öğrenme
            url: https://distancelearning.boun.edu.tr/
          - title: Uluslararası İlişkiler Ofisi
            url: http://intl.boun.edu.tr/

      - title: Kampüs Yaşamı
        links:
          - title: Etkinlik Takvimi
            url: http://takvim.boun.edu.tr/bu/
          - title: Müzik Kampüste
            url: https://klasikmuzik.boun.edu.tr/
          - title: Sinema Kampüste
            url: https://sinebu.boun.edu.tr/
          - title: Kariyer Merkezi
            url: https://kariyermerkezi.boun.edu.tr/
          - title: Bilişim Kulübü
            url: https://www.compec.org/
          - title: Sanal Kampüs Turu
            url: http://sanaltur.boun.edu.tr/

      - title: Diğer Bağlantılar
        links: []

menu:
  top:
    - identifier: resources-university
      name: Üniversite
      url: http://www.boun.edu.tr
      weight: 100
    - identifier: docs
      name: Mevzuat
      url: https://bouncmpedocs.netlify.app
      weight: 200
    - identifier: for_industry
      name: Şirketler için
      url: resources/industry
      weight: 300
    - identifier: news
      name: Haberler
      url: news
      weight: 400
    - identifier: events
      name: Etkinlikler
      url: events
      weight: 500
    - identifier: cmpe492
      name: 491/492
      url: https://bouncmpe-capstone.netlify.app
      weight: 600
    - identifier: donate
      name: Bağış Yapın
      url: donate
      weight: 1000
