languageName: English
title: Department of Computer Engineering | Bogazici University

weight: 2
params:
  logo_text_main: Computer Engineering
  logo_text_top: "Boğaziçi University, Department of"
  powered_by_text: >-
    Powered by [Hugo](https://gohugo.io) and [Bootstrap](https://getbootstrap.com)
  social: []
  footer:
    sections:
      - title: Boğaziçi University
        links:
          - title: Homepage
            url: http://www.boun.edu.tr
          - title: Faculty of Engineering
            url: http://www.eng.boun.edu.tr/
          - title: Institute of Science and Engineering
            url: http://www.fbe.boun.edu.tr
          - title: University Library
            url: https://www.library.boun.edu.tr/
          - title: IT Services
            url: https://cc.boun.edu.tr/
          - title: Campus Map
            url: https://harita.boun.edu.tr/

      - title: Academics
        links:
          - title: Academic Calendar
            url: https://akademiktakvim.boun.edu.tr/
          - title: Registration (BUIS)
            url: https://registration.boun.edu.tr/
          - title: Moodle
            url: https://moodle.boun.edu.tr/
          - title: Distance Learning
            url: https://distancelearning.boun.edu.tr/
          - title: International Relations
            url: http://intl.boun.edu.tr/

      - title: Campus Life
        links:
          - title: Events Calendar
            url: http://takvim.boun.edu.tr/bu/
          - title: Music at Campus
            url: https://klasikmuzik.boun.edu.tr/
          - title: Cinema at Campus
            url: https://sinebu.boun.edu.tr/
          - title: Career Center
            url: https://kariyermerkezi.boun.edu.tr/
          - title: Student IT Club
            url: https://www.compec.org/
          - title: Virtual Campus Tour
            url: http://sanaltur.boun.edu.tr/

      - title: Other Links
        links: []

menu:
  top:
    - identifier: resources-university
      name: University
      url: http://www.boun.edu.tr
      weight: 100
    - identifier: resources-industry
      name: Industry
      url: resources/industry
      weight: 150
    - identifier: docs
      name: Docs
      url: https://bouncmpedocs.netlify.app
      weight: 200
    - identifier: news
      name: News
      url: news
      weight: 400
    - identifier: events
      name: Events
      url: events
      weight: 500
    - identifier: cmpe492
      name: 491/492
      url: https://bouncmpe-capstone.netlify.app
      weight: 600
    - identifier: donate
      name: Donate
      url: donate
      weight: 1000
