backend:
  name: github
  repo: bouncmpe/website-test
  branch: main

# backend:
#   name: git-gateway
# local_backend: true

logo_url: /images/logo.png

media_folder: assets/images/uploads
public_folder: /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

i18n:
  structure: multiple_files
  locales: [en, tr]
  default_locale: en

collections:
  - name: "news"
    label: "Latest News"
    folder: "content/news"
    slug: "{{date}}-news-{{title | lower}}"
    path: "{{year}}/{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    i18n: true
    editor:
      preview: false
    filter: { field: "type", value: "news" }
    fields:
      - {
          label: "Type",
          name: "type",
          widget: "hidden",
          default: "news",
          i18n: "duplicate",
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD MMMM YYYY",
          time_format: false,
          format: "YYYY-MM-DD",
          i18n: "duplicate",
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          i18n: "duplicate",
        }
      - {
          label: "Description",
          name: "body",
          widget: "markdown",
          default: "",
          i18n: true,
        }

  - name: "phd-defense"
    label: "PhD Thesis Defense"
    folder: "content/events"
    slug: "{{expiryDate}}-phd-thesis-defense-{{speaker | lower}}"
    path: "{{year}}/{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    i18n: true
    editor:
      preview: false
    filter: { field: "type", value: "phd-thesis-defense" }
    fields:
      - {
          label: "Type",
          name: "type",
          widget: "hidden",
          default: "phd-thesis-defense",
          i18n: "duplicate",
        }
      - { label: "Thesis Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Speaker",
          name: "speaker",
          widget: "string",
          i18n: "duplicate",
        }
      - {
          label: "Event Date",
          name: "expiryDate",
          widget: "datetime",
          date_format: "DD MMMM YYYY",
          time_format: false,
          format: "YYYY-MM-DD",
          i18n: "duplicate",
        }
      - {
          label: "Start Time",
          name: "startTime",
          widget: "datetime",
          date_format: false,
          time_format: "h:mm A",
          format: "HH:mm",
          i18n: "duplicate",
        }
      - {
          label: "Finish Time",
          name: "finishTime",
          widget: "datetime",
          date_format: false,
          time_format: "h:mm A",
          format: "HH:mm",
          i18n: "duplicate",
        }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          i18n: "duplicate",
        }
      - {
          label: "Meeting Link",
          name: "meeting-link",
          widget: "string",
          i18n: "duplicate",
          required: false,
        }
      - {
          label: "Abstract",
          name: "body",
          widget: "markdown",
          default: "",
          i18n: true,
        }

  - name: "ms-thesis-defense"
    label: "MS Thesis Defense"
    folder: "content/events"
    path: "{{year}}/{{slug}}/index"
    slug: "{{expiryDate}}-ms-thesis-defense-{{speaker | lower}}"
    media_folder: ""
    public_folder: ""
    create: true
    i18n: true
    editor:
      preview: false
    filter: { field: "type", value: "ms-thesis-defense" }
    fields:
      - {
          label: "Type",
          name: "type",
          widget: "hidden",
          default: "ms-thesis-defense",
          i18n: "duplicate",
        }
      - { label: "Thesis Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Speaker",
          name: "speaker",
          widget: "string",
          i18n: "duplicate",
        }
      - {
          label: "Event Date",
          name: "expiryDate",
          widget: "datetime",
          date_format: "DD MMMM YYYY",
          time_format: false,
          format: "YYYY-MM-DD",
          i18n: "duplicate",
        }
      - {
          label: "Start Time",
          name: "startTime",
          widget: "datetime",
          date_format: false,
          time_format: "h:mm A",
          format: "HH:mm",
          i18n: "duplicate",
        }
      - {
          label: "Finish Time",
          name: "finishTime",
          widget: "datetime",
          date_format: false,
          time_format: "h:mm A",
          format: "HH:mm",
          i18n: "duplicate",
        }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          i18n: "duplicate",
        }
      - {
          label: "Meeting Link",
          name: "meeting-link",
          widget: "string",
          i18n: "duplicate",
          required: false,
        }
      - {
          label: "Abstract",
          name: "body",
          widget: "markdown",
          default: "",
          i18n: true,
        }

  - name: "seminar"
    label: "Seminar"
    folder: "content/events"
    slug: "{{expiryDate}}-seminar-{{speaker | lower}}"
    path: "{{year}}/{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    i18n: true
    editor:
      preview: false
    filter: { field: "type", value: "seminar" }
    fields:
      - {
          label: "Type",
          name: "type",
          widget: "hidden",
          default: "seminar",
          i18n: "duplicate",
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Speaker",
          name: "speaker",
          widget: "string",
          i18n: "duplicate",
        }
      - {
          label: "Event Date",
          name: "expiryDate",
          widget: "datetime",
          date_format: "DD MMMM YYYY",
          time_format: false,
          format: "YYYY-MM-DD",
          i18n: "duplicate",
        }
      - {
          label: "Start Time",
          name: "startTime",
          widget: "datetime",
          date_format: false,
          time_format: "h:mm A",
          format: "HH:mm",
          i18n: "duplicate",
        }
      - {
          label: "Finish Time",
          name: "finishTime",
          widget: "datetime",
          date_format: false,
          time_format: "h:mm A",
          format: "HH:mm",
          i18n: "duplicate",
        }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          i18n: "duplicate",
        }
      - {
          label: "Meeting Link",
          name: "meeting-link",
          widget: "string",
          i18n: "duplicate",
          required: false,
        }
      - {
          label: "Description",
          name: "body",
          widget: "markdown",
          default: "",
          i18n: true,
        }
